### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by RushabhJoshi** [bougarfaoui/back#1]
this must be the same issue as [https://github.com/nwjs/nw-builder/issues/75](url)

please suggest you solution

**Comment by bougarfaoui** [comment]
this is because I'm publishing from Windows , 
- go to /modules_node/back-starter/boilerplate/
- copy all files there and paste in your project folder
- this is the skeleton of your app 
- npm install
- npm start

note : this is just a work around , we gonna fix this as soon as possible

**Comment by bougarfaoui** [comment]
The problem should be fixed now.
